### ISSUE TITLE
complete Oar annotation

### ISSUE THREAD

**Issue by ochoaj** [Virtual-Viking-Longship/Ship-Annotations#1]

**Comment by apjmason** [comment]
Reopening. Workflow is to leave issue open until PR is merged and use the keywords fixes or closes and the "#" to close the issue. Review resources linked from [Project Management Course](https://docs.google.com/document/d/1glAb6GyUhPUhaJ5eP1CpK0SdWAIoqtsSvptvN9T9x9I/edit)
